/*
 * Copyright 2026 System Verification Lab, LIACS, Leiden University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Stabiliser generator sets.
 *
 * The stabiliser group of a state v is { G : G|v> = |v> }, and for the states
 * a Pauli-LIMDD node denotes it is generated by at most n signed Pauli words.
 * Putting a node in canonical form means choosing the lexicographically least
 * label for its high edge, and the freedom to choose comes precisely from the
 * stabiliser groups of its two children -- so every node needs its group, and
 * the group has to be cheap to build, to compare and to store.
 *
 * WHY A GROUP HAS EXACTLY ONE HANDLE
 *
 * A generating set is not unique; the group it generates is. Reducing the
 * generators to row reduced echelon form makes the *set* unique too: RREF of
 * the symplectic matrix is a canonical form, so two generating sets span the
 * same group iff their RREFs are identical, row for row.
 *
 * That is what makes the representation here worth having. A set is stored as
 * a hash-consed list -- one llmsset bucket per generator, holding that
 * generator and the handle of the rest -- built from the RREF rows in order.
 * Because the rows are canonical and the list is interned, two states with the
 * same stabiliser group get the SAME handle, and group equality, the operation
 * the canonical form performs constantly, is an integer comparison.
 *
 * The alternative, comparing two sets by reducing both and walking the rows,
 * costs O(n^3) every time it is asked. Here it is paid once, when the group is
 * created.
 *
 * SIGNS
 *
 * A generator is a LIMDD_LIM whose scalar is +1 or -1. Nothing else can
 * stabilise anything: G|v> = |v> forces G to have eigenvalue 1, and a Pauli
 * word squares to the identity, so its scalar squares to 1. Multiplying two
 * generators produces a factor i^k, and k is always even because elements of a
 * stabiliser group commute -- so the product is again signed, never imaginary.
 * limdd_stab_make asserts both facts rather than trusting them.
 *
 * CONCURRENCY
 *
 * Handles are plain 64-bit indices. Reduction happens in a per-worker scratch
 * buffer in thread-local storage, which is private by construction -- separate
 * threads' TLS blocks are separate allocations, so there is no line for two
 * workers to bounce between caches. The only shared state is the llmsset,
 * which is lock-free, so building a group requires a Lace worker but never
 * blocks on one.
 */

#ifndef QSYLVAN_LIMDD_STAB_H
#define QSYLVAN_LIMDD_STAB_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "qsylvan_limdd_lim.h"
#include "qsylvan_limdd_node.h"
#include "qsylvan_limdd_pauli.h"

#ifdef __cplusplus
extern "C" {
#endif

/** An interned stabiliser generator set, in RREF order. */
typedef uint64_t LIMDD_STAB;

/**
 * The trivial group {I}, which every product state that is not a stabiliser
 * state has, and which is therefore by far the most common.
 */
#define LIMDD_STAB_TRIVIAL ((LIMDD_STAB)1)

/** Create the generator set table. Must be called from a Lace worker. */
void limdd_stab_init(size_t stab_tablesize);

/** Destroy the table. */
void limdd_stab_quit(void);

/** Number of list cells in use, which is the total number of generators held. */
size_t limdd_stab_table_count(void);

/** Buckets in the stabiliser cell table, or 0 before it exists. */
size_t limdd_stab_table_size(void);

/**
 * The group generated by `gens`.
 *
 * The generators may be given in any order, may be dependent, and may repeat:
 * they are reduced to RREF first, so the handle depends only on the group.
 * Each must be a LIM with scalar +1 or -1, and they must pairwise commute --
 * an assertion catches both, since a set violating either does not generate a
 * stabiliser group at all.
 *
 * Passing no generators gives LIMDD_STAB_TRIVIAL.
 *
 * Must be called from a Lace worker.
 */
LIMDD_STAB limdd_stab_make(const LIMDD_LIM *gens, size_t ngens);

/** Number of generators, so the group has 2^limdd_stab_ngens elements. */
size_t limdd_stab_ngens(LIMDD_STAB s);

/** The i-th generator in RREF order; i must be below limdd_stab_ngens(s). */
LIMDD_LIM limdd_stab_gen(LIMDD_STAB s, size_t i);

/**
 * The list a group is made of: its first generator, and the group of the
 * rest. Walking with these costs one pointer chase per generator, where
 * calling limdd_stab_gen for each index restarts from the head and costs
 * O(k^2) for the whole list.
 */
LIMDD_LIM  limdd_stab_head(LIMDD_STAB s);
LIMDD_STAB limdd_stab_tail(LIMDD_STAB s);

/** True iff `s` is the trivial group {I}. */
static inline bool
limdd_stab_is_trivial(LIMDD_STAB s)
{
    return s == LIMDD_STAB_TRIVIAL;
}

/**
 * True iff `g` is an element of the group.
 *
 * `g` is reduced against the RREF rows; it belongs iff what remains is exactly
 * the identity, sign included. A word that reduces to the identity with a
 * minus sign means -g is in the group and g is not, which is why the sign
 * cannot be ignored here.
 */
bool limdd_stab_contains(LIMDD_STAB s, LIMDD_LIM g);

/**
 * The group of (|0>+|1>)_from (x) ... (x) (|0>+|1>)_{to-1} (x) |v>, given
 * `s` = Stab(|v>) for a state |v> on qubits to..n-1.
 *
 * That is `s` with one +X_j generator per level in [from, to): X fixes
 * |0>+|1>, nothing else in the Pauli group does up to sign, and the two
 * factors act on disjoint qubits, so the product is direct. It is the group
 * an edge that skips levels from..to-1 has before its label is applied.
 *
 * O(to - from) list cells and no elimination. Every word of `s` lives on
 * qubits >= to, so under the (X | Z) column order all its pivots lie at or
 * beyond column `to`, while each X_j has a single bit at column j < to.
 * Prepending X_from .. X_{to-1} in that order therefore keeps the list in
 * RREF, and the handle is the one limdd_stab_make would give for the same
 * generators -- a test checks that. An assertion checks the precondition.
 *
 * `from == to` returns `s`. Must be called from a Lace worker.
 */
LIMDD_STAB limdd_stab_extend_skipped(LIMDD_STAB s, uint32_t from, uint32_t to);

/**
 * The stabiliser group of the node (var, low, high), from the groups of what
 * its two child edges point at.
 *
 * `s0` and `s1` are the groups of the two bare targets AS READ AT LEVEL
 * var+1: the target node's own group, extended by X_j over every level the
 * child edge skips (limdd_stab_extend_skipped). They are not the groups of the
 * states the edges denote -- the high edge's own label is accounted for here.
 * In a diagram that skips no levels they are simply the child nodes' groups.
 *
 * WHERE THE GROUP COMES FROM
 *
 * The node denotes |0>(x)|v0> + |1>(x)B|v1>, and an operator that fixes it is
 * a Pauli on this qubit tensored with one on the rest. Splitting on the Pauli
 * at this level gives two parts:
 *
 *   diagonal (I or Z here)
 *       Fixes each branch separately, so it needs A|v0> = |v0> and, after
 *       conjugating by B, +-A|v1> = |v1>. That is: the elements of Stab(v0)
 *       whose Pauli word also lies in Stab(v1)'s span -- a SUBGROUP
 *       INTERSECTION over GF(2). Whether I or Z belongs at this level is then
 *       forced, by whether A commutes with B and by the two signs, so every
 *       such A contributes exactly one generator.
 *
 *   anti-diagonal (X or Y here)
 *       Swaps the two branches, so it exists only when |v0> and B|v1> are
 *       isomorphic. With canonical children that happens exactly when the two
 *       edges point at the SAME node, and then only if B's scalar squares to
 *       +-1 -- X when it squares to +1, Y when to -1. One such element
 *       suffices: it is a coset representative, and the rest of the coset is
 *       it times the diagonal part.
 *
 * The Bell node is the smallest case with both: low and high both point at the
 * node for |0>, B = X, giving ZZ from the diagonal part and XX from the
 * anti-diagonal one -- whose product is -YY, the sign that makes the group
 * right.
 *
 * ASSUMES CANONICAL CHILDREN, and this is not a formality. The anti-diagonal
 * test is a comparison of node indices, which stands in for "these children
 * are isomorphic" only once isomorphic nodes have been merged. Hand two
 * children that are isomorphic but stored separately -- |+> and |->, say,
 * which differ by Z -- and the coset is skipped and the group comes back half
 * the size it should be, with no other symptom.
 *
 * Nodes built bottom-up by the canonical form satisfy this by construction,
 * since that is precisely what it establishes. Anything building nodes by hand
 * has to respect it.
 *
 * Once levels can be skipped the anti-diagonal test leans on a second
 * invariant of the canonical form: NO STORED NODE IS SKIPPABLE, i.e. no
 * node's two canonical child edges are equal. With that, two child edges into
 * different targets cannot denote isomorphic states even when the targets sit
 * at different levels -- if they did, the shallower one's cofactors would
 * differ by exactly +-1 and it would have been skipped -- so comparing targets
 * remains the right test.
 *
 * Must be called from a Lace worker.
 */
LIMDD_STAB limdd_stab_of_node(uint32_t var, LIMDD low, LIMDD high,
                              LIMDD_STAB s0, LIMDD_STAB s1);

/**
 * The canonical representative of the class of high-edge labels equivalent
 * to `b`, namely { +-G B H : G in s0, H in s1 }.
 *
 * WHY THAT IS THE CLASS
 *
 * The nodes |0>(x)|v0> + |1>(x)B|v1> and the same with B'' in place of B denote
 * states related by a LIM exactly when B'' = +-G B H for some G in Stab(v0) and
 * H in Stab(v1): G is what the parent LIM does to the low branch, which must
 * leave |v0> alone, and H is the slack in how B acts on |v1>. Picking one
 * representative of that class is what merges two nodes that are the same
 * state in disguise, and so is what makes the diagram canonical.
 *
 * WHY IT IS NOT EXPONENTIAL
 *
 * The class has up to 2^(k0+k1+1) elements, but its WORDS do not: multiplying
 * Pauli words XORs their symplectic vectors, so the words form an affine coset
 * of the span of s0's and s1's words. The least word is then just `b` reduced
 * by an RREF basis of that span -- linear algebra, not enumeration.
 *
 * Once the word is fixed only the scalar is free, and only up to sign: two
 * elements of the class with the same word differ by exactly +-1 (conjugating
 * one decomposition into another contributes a sign and nothing else). So one
 * rule settles it -- the scalar is taken with nonnegative imaginary part, ties
 * broken towards nonnegative real part.
 *
 * WITNESS
 *
 * `*witness` receives the G above, and `*negated` whether the sign rule flipped
 * the result. Together they say what the parent edge must be multiplied by to
 * preserve the state: the Pauli at the node's own level is Z when `*negated`
 * and I otherwise, tensored with G.
 *
 * Must be called from a Lace worker.
 */
LIMDD_LIM limdd_stab_min_coset(LIMDD_LIM b, LIMDD_STAB s0, LIMDD_STAB s1,
                               LIMDD_LIM *witness, bool *negated);

/**
 * Write the `k`-th element of the group, for k in 0..2^ngens-1, taking bit i
 * of k as "include generator i".
 *
 * This enumerates the whole group, so it is exponential and meant for tests
 * and for small groups, not for the hot path.
 */
LIMDD_LIM limdd_stab_element(LIMDD_STAB s, uint64_t k);

/* --- garbage collection --------------------------------------------------- */

/** Mark `s` live, with its list cells and every generator in it. */
void limdd_gc_mark_stab(LIMDD_STAB s);

/** Forget which buckets are occupied. */
void limdd_gc_clear_stabs(void);

/** Rebuild the hash array over the marked buckets. */
void limdd_gc_rehash_stabs(void);

/** Print the generators to `out`, one per line, each indented by `indent`. */
void limdd_stab_fprint(FILE *out, LIMDD_STAB s, const char *indent);

#ifdef __cplusplus
}
#endif

#endif // QSYLVAN_LIMDD_STAB_H
